//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public long id { get; set; }
        public Nullable<long> cityid { get; set; }
        public string areaname { get; set; }
        public string areacode { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    }
}
