//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance_finalize_department
    {
        public int ID { get; set; }
        public string e_date { get; set; }
        public string e_id { get; set; }
        public string @in { get; set; }
        public string @out { get; set; }
        public string deptid { get; set; }
        public Nullable<int> workhrs { get; set; }
        public Nullable<int> workmts { get; set; }
        public string extratime { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
        public string Attr3 { get; set; }
    }
}
