//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance_log_department_MHS
    {
        public int id { get; set; }
        public string e_date { get; set; }
        public string e_id { get; set; }
        public string e_name { get; set; }
        public string @in { get; set; }
        public string @out { get; set; }
        public string outdate { get; set; }
        public string deptid { get; set; }
        public string lout { get; set; }
        public string lin { get; set; }
        public Nullable<int> workedhrs { get; set; }
        public Nullable<int> workedmts { get; set; }
        public Nullable<int> lunchhrs { get; set; }
        public Nullable<int> lunchmts { get; set; }
        public Nullable<int> InVariance { get; set; }
        public Nullable<int> OutVariance { get; set; }
        public string Status { get; set; }
    }
}
