//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cAccessTime
    {
        public string C_Code { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> L_Flag { get; set; }
        public string C_Holiday { get; set; }
        public string C_Sun { get; set; }
        public string C_Mon { get; set; }
        public string C_The { get; set; }
        public string C_Wed { get; set; }
        public string C_Thu { get; set; }
        public string C_Fri { get; set; }
        public string C_Sat { get; set; }
        public string C_Hol { get; set; }
        public string C_Remark { get; set; }
    }
}
