//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cAccessArea
    {
        public string C_Code { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> L_Flag { get; set; }
        public string C_Remark { get; set; }
        public string C_AccessTime { get; set; }
        public string C_AccessTime2 { get; set; }
        public string C_AccessTime3 { get; set; }
        public string C_AccessTime4 { get; set; }
    }
}
