//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cAuthority
    {
        public string C_Code { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> L_SetLocal { get; set; }
        public Nullable<int> L_RegInfo { get; set; }
        public Nullable<int> L_DataBackup { get; set; }
        public Nullable<int> L_MgrTerminal { get; set; }
        public Nullable<int> L_RegControl { get; set; }
        public Nullable<int> L_SetControl { get; set; }
        public Nullable<int> L_RegEmploye { get; set; }
        public Nullable<int> L_ModEmploye { get; set; }
        public Nullable<int> L_OutEmploye { get; set; }
        public Nullable<int> L_RegVisitor { get; set; }
        public Nullable<int> L_OutVisitor { get; set; }
        public Nullable<int> L_RegMoney { get; set; }
        public Nullable<int> L_RegWork { get; set; }
        public Nullable<int> L_SetWork { get; set; }
        public Nullable<int> L_ModWork { get; set; }
        public Nullable<int> L_RegMeal { get; set; }
        public Nullable<int> L_SetMeal { get; set; }
        public Nullable<int> L_ModMeal { get; set; }
        public Nullable<int> L_DelResult { get; set; }
        public Nullable<int> L_DelWork { get; set; }
        public Nullable<int> L_DelMeal { get; set; }
        public Nullable<int> L_MgrScope { get; set; }
        public Nullable<int> L_ChgBlacklist { get; set; }
        public Nullable<int> L_RelBlacklist { get; set; }
        public Nullable<int> L_ModBlacklist { get; set; }
        public Nullable<int> L_DelBlacklist { get; set; }
        public Nullable<int> L_Customized { get; set; }
        public Nullable<int> L_RegAdmin { get; set; }
        public Nullable<int> L_ModAdmin { get; set; }
        public Nullable<int> L_SetShutdown { get; set; }
        public Nullable<int> L_MntMgr { get; set; }
        public Nullable<int> L_MntClient { get; set; }
        public Nullable<int> L_MntTerminal { get; set; }
        public Nullable<int> L_MntAuthLog { get; set; }
        public Nullable<int> L_MntEvent { get; set; }
        public Nullable<int> L_TmnMgr { get; set; }
        public Nullable<int> L_TmnAdd { get; set; }
        public Nullable<int> L_TmnMod { get; set; }
        public Nullable<int> L_TmnDel { get; set; }
        public Nullable<int> L_TmnUpgrade { get; set; }
        public Nullable<int> L_TmnOption { get; set; }
        public Nullable<int> L_TmnAdmin { get; set; }
        public Nullable<int> L_TmnSendFile { get; set; }
        public Nullable<int> L_EmpMgr { get; set; }
        public Nullable<int> L_EmpAdd { get; set; }
        public Nullable<int> L_EmpMod { get; set; }
        public Nullable<int> L_EmpDel { get; set; }
        public Nullable<int> L_EmpSendTerminal { get; set; }
        public Nullable<int> L_EmpTerminalMng { get; set; }
        public Nullable<int> L_EmpRegAdmin { get; set; }
        public Nullable<int> L_VstMgr { get; set; }
        public Nullable<int> L_VstAdd { get; set; }
        public Nullable<int> L_VstMod { get; set; }
        public Nullable<int> L_VstDel { get; set; }
        public Nullable<int> L_BlckMgr { get; set; }
        public Nullable<int> L_BlckChange { get; set; }
        public Nullable<int> L_BlckRelease { get; set; }
        public Nullable<int> L_BlckDel { get; set; }
        public Nullable<int> L_BlckMod { get; set; }
        public Nullable<int> L_AccMgr { get; set; }
        public Nullable<int> L_AccSet { get; set; }
        public Nullable<int> L_MapMgr { get; set; }
        public Nullable<int> L_MapSet { get; set; }
        public Nullable<int> L_TnaMgr { get; set; }
        public Nullable<int> L_TnaSet { get; set; }
        public Nullable<int> L_TnaSpecial { get; set; }
        public Nullable<int> L_TnaWork { get; set; }
        public Nullable<int> L_TnaOutState { get; set; }
        public Nullable<int> L_TnaOutExcRecord { get; set; }
        public Nullable<int> L_TnaSummary { get; set; }
        public Nullable<int> L_TnaSendResult { get; set; }
        public Nullable<int> L_TnaDelData { get; set; }
        public Nullable<int> L_MealMgr { get; set; }
        public Nullable<int> L_MealOutRecord { get; set; }
        public Nullable<int> L_MealDelData { get; set; }
        public Nullable<int> L_MealOutDept { get; set; }
        public Nullable<int> L_MealOutPerson { get; set; }
        public Nullable<int> L_MealSet { get; set; }
        public Nullable<int> L_LogMgr { get; set; }
        public Nullable<int> L_LogOutRecord { get; set; }
        public Nullable<int> L_LogDelRecord { get; set; }
        public Nullable<int> L_SetRegInfo { get; set; }
        public Nullable<int> L_SetMgr { get; set; }
        public Nullable<int> L_SetServer { get; set; }
        public Nullable<int> L_SetPwd { get; set; }
        public Nullable<int> L_SetMail { get; set; }
        public Nullable<int> L_SetEtc { get; set; }
    }
}
