//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerDetail
    {
        public long id { get; set; }
        public Nullable<long> reflogin { get; set; }
        public string EmployerName { get; set; }
        public string Durationfrom { get; set; }
        public string Durationto { get; set; }
        public string Designation { get; set; }
        public string JobProfile { get; set; }
        public Nullable<long> NoticePeriod { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<long> employertype { get; set; }
    }
}
