//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPMASTER
    {
        public string skyid { get; set; }
        public string title { get; set; }
        public string FIRSTANME { get; set; }
        public string MIDDILENAME { get; set; }
        public string LASTNAME { get; set; }
        public string OFFICEEMAID { get; set; }
        public string isactive { get; set; }
        public string prttime { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string empid { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<System.DateTime> anniversary { get; set; }
        public Nullable<int> maritialstatus { get; set; }
    }
}
