//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_AccessMaster
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Menu_Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedIP { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
    
        public virtual TB_MainMenu TB_MainMenu { get; set; }
    }
}
