//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_AVAIL_SCHEDULE
    {
        public int SC_ID { get; set; }
        public string SCHEDULE { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string HOST_N { get; set; }
        public string Frequency { get; set; }
        public string Weekids { get; set; }
    }
}
