//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Attendance_Transaction
    {
        public int Id { get; set; }
        public string User_Type { get; set; }
        public Nullable<int> User_Id { get; set; }
        public int Class_Id { get; set; }
        public string P_Trans { get; set; }
        public string Op_Date { get; set; }
        public string Op_Time { get; set; }
        public string Host_Name { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
        public string Attr3 { get; set; }
    }
}
