//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DAYS_WORKED
    {
        public long ID { get; set; }
        public string PERSON_ID { get; set; }
        public Nullable<int> DEPT { get; set; }
        public Nullable<System.DateTime> ATT_FROM { get; set; }
        public Nullable<System.DateTime> ATT_TO { get; set; }
        public Nullable<int> AYEAR { get; set; }
        public Nullable<int> PRESENT { get; set; }
        public Nullable<int> ABSENT { get; set; }
        public Nullable<int> PAYROLLID { get; set; }
        public Nullable<int> ANP { get; set; }
        public Nullable<int> SKP { get; set; }
        public Nullable<int> MTP { get; set; }
        public Nullable<int> CLP { get; set; }
        public Nullable<int> BUT { get; set; }
        public Nullable<int> HAP { get; set; }
        public Nullable<int> SKU { get; set; }
        public Nullable<int> ANU { get; set; }
        public Nullable<int> MTU { get; set; }
        public Nullable<int> HAU { get; set; }
        public Nullable<int> CAU { get; set; }
    }
}
