//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DEPARTMENT
    {
        public int DEPARTMENT_ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string REPORTING_TO_DEPT_ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> ACTIVE_FLAG { get; set; }
        public Nullable<int> UPDATED_BY_ID { get; set; }
        public Nullable<System.DateTime> UPDATION_TIME { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string HOST_N { get; set; }
        public Nullable<int> STATUS_PER_TEMP { get; set; }
        public Nullable<int> MAIN_DEPT { get; set; }
        public Nullable<int> ORG_ID { get; set; }
        public string SCHOOL_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public Nullable<bool> ACTIVE_TPS { get; set; }
        public string EMAIL { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public Nullable<int> CREATED_BY_ID { get; set; }
        public Nullable<System.DateTime> CREATION_TIME { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
