//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Grade_Detail
    {
        public long GradeDetailID { get; set; }
        public int FY_ID { get; set; }
        public int Grade_ID { get; set; }
        public Nullable<double> Basic_Min { get; set; }
        public Nullable<double> Basic_Max { get; set; }
        public Nullable<double> Social_Min { get; set; }
        public Nullable<double> Social_Max { get; set; }
        public Nullable<double> CT_Min { get; set; }
        public Nullable<double> CT_Max { get; set; }
        public Nullable<double> Accomadation_Min { get; set; }
        public Nullable<double> Accomadation_max { get; set; }
        public Nullable<double> Admin_MIn { get; set; }
        public Nullable<double> Admin_Max { get; set; }
        public Nullable<double> Annual_increment { get; set; }
        public Nullable<double> Noof_increment { get; set; }
        public Nullable<double> Noof_incentive_pay { get; set; }
        public Nullable<double> Minpayrange { get; set; }
        public Nullable<double> MaxPayrange { get; set; }
        public Nullable<double> Monthly_Acc { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> updated_userid { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
    }
}
