//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_POSITION
    {
        public int POSITION_ID { get; set; }
        public string POSITION_NAME { get; set; }
        public string REPORTING_TO_DEPT_ID { get; set; }
        public Nullable<int> SHAREPOINT_DISPLAY_MAINDEPT { get; set; }
        public Nullable<int> ORG_ID { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
    }
}
