//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iMeal
    {
        public string C_Code { get; set; }
        public string C_Name { get; set; }
        public int L_MealType { get; set; }
        public Nullable<int> L_MealLimit { get; set; }
        public string C_MealTime1 { get; set; }
        public string C_MealTime2 { get; set; }
        public string C_StatsDate { get; set; }
    }
}
