//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iMealPay
    {
        public int L_MealType { get; set; }
        public Nullable<int> L_Menu1 { get; set; }
        public Nullable<int> L_Menu2 { get; set; }
        public Nullable<int> L_Menu3 { get; set; }
        public Nullable<int> L_Menu4 { get; set; }
    }
}
