//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iPassback
    {
        public int L_TID { get; set; }
        public int L_RID { get; set; }
        public string C_AreaIn { get; set; }
        public string C_AreaOut { get; set; }
        public Nullable<int> L_Type { get; set; }
        public string C_LockoutTime { get; set; }
        public string C_Remark { get; set; }
    }
}
