//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iUserMobileKey
    {
        public int L_UID { get; set; }
        public string C_MobilePhone { get; set; }
        public string C_CountryCode { get; set; }
        public Nullable<int> L_KeyType { get; set; }
        public string C_ImkeyPeriod { get; set; }
        public Nullable<int> L_issuecount { get; set; }
        public string C_KeyNo { get; set; }
        public Nullable<int> L_NowIssue { get; set; }
        public byte[] B_UUID { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
