//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iUserCard
    {
        public string C_CardNum { get; set; }
        public Nullable<int> L_UID { get; set; }
        public Nullable<int> L_DataCheck { get; set; }
    }
}
