//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iZoneInfo
    {
        public int L_TID { get; set; }
        public int L_Index { get; set; }
        public int L_Zone { get; set; }
        public string C_Name { get; set; }
    }
}
