//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAccessShiftSchedule
    {
        public string C_AccessGroup { get; set; }
        public string C_BasicDate { get; set; }
        public Nullable<int> L_SpinDays { get; set; }
        public string C_ShiftCode { get; set; }
    }
}
