//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAuditServer
    {
        public string C_EventTime { get; set; }
        public int L_LogonID { get; set; }
        public Nullable<int> L_Section { get; set; }
        public string C_Target { get; set; }
        public Nullable<int> L_Process { get; set; }
        public Nullable<int> L_Detail { get; set; }
    }
}
