//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAuditTerminal
    {
        public string C_EventTime { get; set; }
        public int L_TID { get; set; }
        public int L_AdminID { get; set; }
        public string C_AdminName { get; set; }
        public int L_Type { get; set; }
        public int L_UserID { get; set; }
        public string C_UserName { get; set; }
    }
}
