//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAutoDown
    {
        public string C_RegTime { get; set; }
        public int L_CID { get; set; }
        public int L_Index { get; set; }
        public Nullable<int> L_Target { get; set; }
        public Nullable<int> L_Process { get; set; }
        public Nullable<int> L_TID { get; set; }
        public Nullable<int> L_UID { get; set; }
        public string C_AccessGroup { get; set; }
        public string C_OfficeCode { get; set; }
        public int L_RetryCount { get; set; }
        public Nullable<int> L_DataCheck { get; set; }
    }
}
