//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_designation
    {
        public int id { get; set; }
        public string desigid { get; set; }
        public string designation { get; set; }
        public string deptid { get; set; }
        public string IsActive { get; set; }
    }
}
