//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_EmpRemarks
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public string EDate { get; set; }
        public string Remarks { get; set; }
        public string UserName { get; set; }
        public string HostID { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    }
}
