//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PartimeFacultyAtt
    {
        public int Id { get; set; }
        public int Empid { get; set; }
        public string Date { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string Attendence { get; set; }
        public string Remarks { get; set; }
        public string MacAddress { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMacAddress { get; set; }
    }
}
