//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Presenttemp
    {
        public Nullable<int> Empid { get; set; }
        public string Date { get; set; }
        public string Attr1 { get; set; }
        public Nullable<int> Attr2 { get; set; }
        public string Attr3 { get; set; }
        public int Id { get; set; }
    }
}
