//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SessionRecord
    {
        public int ID { get; set; }
        public Nullable<int> L_UID { get; set; }
        public Nullable<int> ASession { get; set; }
        public Nullable<int> PSession { get; set; }
        public string vDate { get; set; }
        public Nullable<int> Batch_id { get; set; }
        public Nullable<int> HolidaySession { get; set; }
        public Nullable<int> DailyAttendance { get; set; }
    }
}
