//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Shiftcontract
    {
        public int shift_id { get; set; }
        public string Shift_name { get; set; }
        public string Shift_code { get; set; }
        public string attr1 { get; set; }
        public string attr2 { get; set; }
        public string attr3 { get; set; }
        public string attr4 { get; set; }
        public string attr5 { get; set; }
        public string attr6 { get; set; }
        public string attr7 { get; set; }
        public string attr8 { get; set; }
        public string attr9 { get; set; }
        public string attr10 { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string HostName { get; set; }
    }
}
