//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RFID_CARDENTRY_DELETED
    {
        public int id { get; set; }
        public Nullable<int> CARDID { get; set; }
        public string STUD_ID { get; set; }
        public string L_UID { get; set; }
        public string STUDENT_NAME { get; set; }
        public string DEGREECODE { get; set; }
        public string SHIFT { get; set; }
        public string MOBILENO { get; set; }
        public string PLATENO { get; set; }
        public string PLATENO2 { get; set; }
        public string CARDNO { get; set; }
        public Nullable<bool> CARDISSUED { get; set; }
        public string CARD_INFO_NO { get; set; }
        public string REMARKS { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_IP { get; set; }
        public string OPERATION { get; set; }
    }
}
