//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StaffLoanORSalaryAdvance
    {
        public int StaffLOSAdvId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string FullName { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ModeOfPayment { get; set; }
        public string ReasonOfrequest { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
        public string Attr3 { get; set; }
        public string Attr4 { get; set; }
        public string Attr5 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedHost { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ApplicationType { get; set; }
    }
}
