//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OUTDOOR_EVENTS
    {
        public int Event_Id { get; set; }
        public Nullable<int> Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<int> Terminal_id { get; set; }
        public string Mode { get; set; }
        public string From_date { get; set; }
        public string To_Date { get; set; }
        public string Location { get; set; }
        public string Country { get; set; }
        public string Remarks { get; set; }
    }
}
