//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeShiftDtl
    {
        public int EMPSHIFTDtlID { get; set; }
        public int EMPSHIFTID { get; set; }
        public int WeekDayNo { get; set; }
        public string WeekDayName { get; set; }
        public int SHIFTID { get; set; }
        public bool IsHoliday { get; set; }
    }
}
