//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPerson()
        {
            this.tblContacts = new HashSet<tblContact>();
        }
    
        public int PersonId { get; set; }
        public string EmpNumber { get; set; }
        public Nullable<int> MachineCode { get; set; }
        public Nullable<int> Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> EmpStatus { get; set; }
        public Nullable<System.DateTime> EndOfService { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public Nullable<int> Reason { get; set; }
        public string Remarks { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
        public string Attr3 { get; set; }
        public string Attr4 { get; set; }
        public string Attr5 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedHost { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> OrgTypeId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<bool> IsInternationalEmployee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContact> tblContacts { get; set; }
    }
}
