//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorkLog()
        {
            this.tblWorkLogBatchDtls = new HashSet<tblWorkLogBatchDtl>();
            this.tblWorkLogDtls = new HashSet<tblWorkLogDtl>();
        }
    
        public int WLID { get; set; }
        public int EmpNumber { get; set; }
        public int L_UID { get; set; }
        public System.DateTime LogDate { get; set; }
        public int ShiftID { get; set; }
        public int AWH { get; set; }
        public int AWM { get; set; }
        public int ACS { get; set; }
        public bool ISOTApplicable { get; set; }
        public int AEH { get; set; }
        public int AEM { get; set; }
        public int WH { get; set; }
        public int WM { get; set; }
        public int CS { get; set; }
        public int EH { get; set; }
        public int EM { get; set; }
        public string PresentStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> LeaveID { get; set; }
        public bool IsActive { get; set; }
        public string DayType { get; set; }
        public bool OutDoorEvent { get; set; }
        public int OH { get; set; }
        public int OM { get; set; }
        public bool OffDayDuty { get; set; }
        public Nullable<bool> isholiday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkLogBatchDtl> tblWorkLogBatchDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkLogDtl> tblWorkLogDtls { get; set; }
    }
}
