//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeekendSchedule_log
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string CalDate { get; set; }
        public Nullable<int> DayType { get; set; }
        public string Remarks { get; set; }
        public string attr1 { get; set; }
        public string attr2 { get; set; }
        public string attr3 { get; set; }
        public string attr4 { get; set; }
        public string attr5 { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Host_Name { get; set; }
        public Nullable<bool> CurrentCurriculum { get; set; }
        public Nullable<bool> RTP { get; set; }
        public Nullable<bool> PayConfirmed { get; set; }
        public Nullable<System.DateTime> Paycreateddate { get; set; }
        public string PayCreatedIP { get; set; }
        public string PayVoucherNo { get; set; }
        public Nullable<int> PayCreatedby { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string MacAddress { get; set; }
        public string ModMacAddress { get; set; }
    }
}
