//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorklog_Shift
    {
        public int Logid { get; set; }
        public Nullable<int> Worklogid { get; set; }
        public Nullable<int> empshiftid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
