//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkLogDtl_20180915
    {
        public int WLDtlID { get; set; }
        public int WLID { get; set; }
        public int ShiftDtlID { get; set; }
        public int AWH { get; set; }
        public int AWM { get; set; }
        public int ACS { get; set; }
        public int AEH { get; set; }
        public int AEM { get; set; }
        public int WH { get; set; }
        public int WM { get; set; }
        public int CS { get; set; }
        public int EH { get; set; }
        public int EM { get; set; }
        public string PresentStatus { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public string INTIME { get; set; }
        public string OUTTIME { get; set; }
        public bool OutDoorEvent { get; set; }
        public int OH { get; set; }
        public int OM { get; set; }
    }
}
