//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChangedInfo
    {
        public string C_CreateTime { get; set; }
        public int L_Target { get; set; }
        public int L_Procedure { get; set; }
        public int L_TargetID { get; set; }
        public string C_TargetCode { get; set; }
        public Nullable<int> L_ClientID { get; set; }
    }
}
