//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCmdDown
    {
        public string C_RegTime { get; set; }
        public int L_TID { get; set; }
        public int L_UID { get; set; }
        public string C_Time { get; set; }
        public byte[] B_Data { get; set; }
        public Nullable<int> L_Retry { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
