//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmploye
    {
        public int L_UID { get; set; }
        public string C_IncludeDate { get; set; }
        public string C_RetiredDate { get; set; }
        public string C_Office { get; set; }
        public string C_Post { get; set; }
        public string C_Staff { get; set; }
        public string C_Authority { get; set; }
        public string C_Work { get; set; }
        public string C_Money { get; set; }
        public string C_Meal { get; set; }
        public string C_Phone { get; set; }
        public string C_Email { get; set; }
        public string C_Address { get; set; }
        public string C_Remark { get; set; }
    }
}
