//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEnter_log
    {
        public int ID { get; set; }
        public string C_Date { get; set; }
        public string C_Time { get; set; }
        public int L_TID { get; set; }
        public int L_UID { get; set; }
        public string C_Name { get; set; }
        public string C_Unique { get; set; }
        public string C_Office { get; set; }
        public string C_Post { get; set; }
        public string C_Card { get; set; }
        public Nullable<int> L_UserType { get; set; }
        public Nullable<int> L_Mode { get; set; }
        public Nullable<int> L_MatchingType { get; set; }
        public Nullable<int> L_Result { get; set; }
        public Nullable<int> L_IsPicture { get; set; }
        public Nullable<int> L_Device { get; set; }
        public Nullable<int> L_OverCount { get; set; }
        public string C_Property { get; set; }
        public Nullable<int> L_JobCode { get; set; }
        public Nullable<int> L_Etc { get; set; }
        public Nullable<int> L_Trans { get; set; }
        public string upload { get; set; }
    }
}
