//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHourlyCount
    {
        public string C_Date { get; set; }
        public int L_Time { get; set; }
        public string C_Office { get; set; }
        public int L_TID { get; set; }
        public int L_SensorNo { get; set; }
        public int L_Zone { get; set; }
        public Nullable<int> L_InCount { get; set; }
        public Nullable<int> L_OutCount { get; set; }
        public string C_CreateDate { get; set; }
    }
}
