//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMapImage
    {
        public string C_Code { get; set; }
        public string C_Name { get; set; }
        public string C_FileName { get; set; }
        public Nullable<int> L_FileSize { get; set; }
        public byte[] B_FileData { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
