//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMoney
    {
        public string C_Code { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> L_PayUnit { get; set; }
        public Nullable<double> D_WT1Money { get; set; }
        public Nullable<double> D_WT2Money { get; set; }
        public Nullable<double> D_WT3Money { get; set; }
        public Nullable<double> D_WT4Money { get; set; }
        public Nullable<double> D_WT5Money { get; set; }
        public Nullable<double> D_WT6Money { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
