//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTerminal
    {
        public int L_ID { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> L_FnWork { get; set; }
        public Nullable<int> L_FnMeal { get; set; }
        public Nullable<int> L_FnSchool { get; set; }
        public string C_Office { get; set; }
        public string C_Place { get; set; }
        public string C_RegDate { get; set; }
        public Nullable<int> L_CommType { get; set; }
        public string C_IPAddr { get; set; }
        public Nullable<int> L_IPPort { get; set; }
        public Nullable<int> L_ComPort { get; set; }
        public Nullable<int> L_Baudrate { get; set; }
        public Nullable<int> L_Passback { get; set; }
        public string C_AreaIn { get; set; }
        public string C_AreaOut { get; set; }
        public string C_lastup { get; set; }
        public string C_Version { get; set; }
        public string C_Remark { get; set; }
        public Nullable<int> L_RemoteCtrl { get; set; }
        public string C_MacAddr { get; set; }
        public Nullable<int> L_tzUseFlag { get; set; }
        public Nullable<int> L_tzIndex { get; set; }
        public Nullable<int> L_tzBias { get; set; }
        public string C_tzKeyName { get; set; }
        public Nullable<int> L_Status { get; set; }
        public Nullable<int> L_InstallType { get; set; }
        public Nullable<int> L_VTerminalID { get; set; }
        public Nullable<int> L_DataCheck { get; set; }
        public Nullable<int> L_SoftPassback { get; set; }
        public Nullable<int> L_Type { get; set; }
        public string C_PartitionStatus { get; set; }
        public string C_ZoneStatus { get; set; }
        public string C_LockStatus { get; set; }
        public string C_ReaderStatus { get; set; }
        public string C_ReaderVer1 { get; set; }
        public string C_ReaderVer2 { get; set; }
        public string C_ReaderVer3 { get; set; }
        public string C_ReaderVer4 { get; set; }
        public string C_ReaderVer5 { get; set; }
        public string C_ReaderVer6 { get; set; }
        public string C_ReaderVer7 { get; set; }
        public string C_ReaderVer8 { get; set; }
        public string C_ReaderName0 { get; set; }
        public string C_ReaderName1 { get; set; }
        public string C_ReaderName2 { get; set; }
        public string C_ReaderName3 { get; set; }
        public string C_ReaderName4 { get; set; }
        public string C_ReaderName5 { get; set; }
        public string C_ReaderName6 { get; set; }
        public string C_ReaderName7 { get; set; }
        public Nullable<int> L_AuthType { get; set; }
        public Nullable<int> L_DVRID { get; set; }
        public Nullable<int> L_Chnl1 { get; set; }
        public Nullable<int> L_Chnl2 { get; set; }
    }
}
