//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTerminalStateLog
    {
        public string C_EventTime { get; set; }
        public int L_TID { get; set; }
        public int L_UID { get; set; }
        public int L_Class { get; set; }
        public int L_Detail { get; set; }
        public Nullable<int> L_SensorNo { get; set; }
        public Nullable<int> L_TargetID { get; set; }
        public Nullable<int> L_Partition { get; set; }
        public Nullable<int> L_Account { get; set; }
        public Nullable<int> L_Qualifier { get; set; }
        public string C_EventInfo { get; set; }
    }
}
