//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        public int L_ID { get; set; }
        public string C_Name { get; set; }
        public string C_Unique { get; set; }
        public Nullable<int> L_Type { get; set; }
        public string C_RegDate { get; set; }
        public Nullable<int> L_OptDateLimit { get; set; }
        public string C_DateLimit { get; set; }
        public Nullable<int> L_AccessType { get; set; }
        public string C_Password { get; set; }
        public Nullable<int> L_Identify { get; set; }
        public Nullable<int> L_VerifyLevel { get; set; }
        public string C_AccessGroup { get; set; }
        public string C_PassbackStatus { get; set; }
        public Nullable<int> L_VOIPUsed { get; set; }
        public Nullable<int> L_DoorOpen { get; set; }
        public Nullable<int> L_AutoAnswer { get; set; }
        public Nullable<int> L_EnableMeta1 { get; set; }
        public Nullable<int> L_RingCount1 { get; set; }
        public string C_LoginID1 { get; set; }
        public string C_SipAddr1 { get; set; }
        public Nullable<int> L_EnableMeta2 { get; set; }
        public Nullable<int> L_RingCount2 { get; set; }
        public string C_LoginID2 { get; set; }
        public string C_SipAddr2 { get; set; }
        public string C_UserMessage { get; set; }
        public Nullable<int> L_Blacklist { get; set; }
        public Nullable<int> L_IsNotice { get; set; }
        public string C_Notice { get; set; }
        public string C_PassbackTime { get; set; }
        public Nullable<int> L_ExceptPassback { get; set; }
        public Nullable<int> L_DataCheck { get; set; }
        public Nullable<int> L_Partition { get; set; }
        public Nullable<int> L_FaceIdentify { get; set; }
        public byte[] B_DuressFinger { get; set; }
        public Nullable<int> L_AuthValue { get; set; }
        public string C_RemotePW { get; set; }
        public Nullable<int> L_WrongCount { get; set; }
        public Nullable<int> L_LogonLocked { get; set; }
        public string C_LogonDateTime { get; set; }
        public string C_UdatePassword { get; set; }
        public string C_MustChgPwd { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
