//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVisitor
    {
        public int L_UID { get; set; }
        public string C_Office { get; set; }
        public string C_Post { get; set; }
        public string C_Target { get; set; }
        public string C_Goal { get; set; }
        public string C_Company { get; set; }
        public string C_Info { get; set; }
        public string C_Phone { get; set; }
        public string C_Email { get; set; }
        public string C_Address { get; set; }
        public string C_Remark { get; set; }
    }
}
