//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPerson
    {
        public int PersonId { get; set; }
        public string EmpNumber { get; set; }
        public string JoinDate { get; set; }
        public Nullable<int> MachineCode { get; set; }
        public string TITLE { get; set; }
        public string NAME { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> EmpStatus { get; set; }
        public string LocationId { get; set; }
        public string LOCATION { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string JOB_NAME { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public Nullable<int> DEPARTMENT_ID { get; set; }
        public string OrgId { get; set; }
        public string ORGANIZATION_NAME { get; set; }
        public string EndOfService { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string COUNTRY_NAME { get; set; }
        public string Section { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> Type { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<int> SHIFT_ID { get; set; }
        public string SHIFT_NAME { get; set; }
        public string GENDER { get; set; }
        public string COuntryOfBirth { get; set; }
        public string EMPSTATUSDesc { get; set; }
        public Nullable<int> Category { get; set; }
        public string BloodGroupDesc { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string GradeName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> OfficeExtn { get; set; }
        public string OfficeMail { get; set; }
        public string RoomNo { get; set; }
        public Nullable<int> IsFullTime { get; set; }
        public string Expr1 { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public int EmpStatusId { get; set; }
        public string CATEGORYNAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> EOS { get; set; }
        public string Weekids { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string ProbationPeriod { get; set; }
        public string SHIFT_FROM { get; set; }
        public string SHIFT_TO { get; set; }
        public Nullable<int> MaritialStatus { get; set; }
        public Nullable<System.DateTime> Anniversary { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<bool> IsProbation { get; set; }
        public int SHAREPOINT_DISPLAY_MAINDEPTID { get; set; }
        public string SHAREPOINT_DISPLAY_MAINDEPTNAME { get; set; }
    }
}
