//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vtuser
    {
        public int L_ID { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> E_DEPT_ID { get; set; }
        public Nullable<int> E_DES_ID { get; set; }
        public Nullable<int> E_BRANCH_ID { get; set; }
        public string Department { get; set; }
    }
}
