//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wExceptRecord
    {
        public Nullable<int> L_UID { get; set; }
        public string C_Name { get; set; }
        public string C_Unique { get; set; }
        public string C_OfficeCode { get; set; }
        public string C_OfficeName { get; set; }
        public string C_PostCode { get; set; }
        public string C_PostName { get; set; }
        public string C_StaffCode { get; set; }
        public string C_StaffName { get; set; }
        public string C_WorkDate { get; set; }
        public string C_ShiftCode { get; set; }
        public string C_ShiftName { get; set; }
        public Nullable<int> L_ExceptType { get; set; }
        public Nullable<int> L_ExceptTM1 { get; set; }
        public Nullable<int> L_ExceptTM2 { get; set; }
        public Nullable<int> L_ExceptTime { get; set; }
    }
}
