//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wTempWorkResult
    {
        public string C_WorkDate { get; set; }
        public int L_UID { get; set; }
        public int L_AccessTime { get; set; }
        public int L_Mode { get; set; }
    }
}
