//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wWorkSummary
    {
        public string C_SumDate { get; set; }
        public int L_UID { get; set; }
        public string C_Name { get; set; }
        public string C_Unique { get; set; }
        public string C_OfficeCode { get; set; }
        public string C_OfficeName { get; set; }
        public string C_PostCode { get; set; }
        public string C_PostName { get; set; }
        public string C_StaffCode { get; set; }
        public string C_StaffName { get; set; }
        public string C_WorkCode { get; set; }
        public string C_WorkName { get; set; }
        public string C_Period1 { get; set; }
        public string C_Period2 { get; set; }
        public Nullable<int> L_Latetime { get; set; }
        public Nullable<int> L_LackTime { get; set; }
        public Nullable<int> L_ST1Late { get; set; }
        public Nullable<int> L_ST1Lack { get; set; }
        public Nullable<int> L_ST1Time { get; set; }
        public Nullable<int> L_ST2Late { get; set; }
        public Nullable<int> L_ST2Lack { get; set; }
        public Nullable<int> L_ST2Time { get; set; }
        public Nullable<int> L_ST3Late { get; set; }
        public Nullable<int> L_ST3Lack { get; set; }
        public Nullable<int> L_ST3Time { get; set; }
        public Nullable<int> L_ST4Late { get; set; }
        public Nullable<int> L_ST4Lack { get; set; }
        public Nullable<int> L_ST4Time { get; set; }
        public Nullable<int> L_ST5Late { get; set; }
        public Nullable<int> L_ST5Lack { get; set; }
        public Nullable<int> L_ST5Time { get; set; }
        public Nullable<int> L_ST6Late { get; set; }
        public Nullable<int> L_ST6Lack { get; set; }
        public Nullable<int> L_ST6Time { get; set; }
        public Nullable<double> D_PayMoney { get; set; }
        public Nullable<int> L_Modify { get; set; }
        public string C_Remark { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
