//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wWorkResult
    {
        public string C_WorkDate { get; set; }
        public int L_UID { get; set; }
        public string C_Name { get; set; }
        public string C_Unique { get; set; }
        public string C_OfficeCode { get; set; }
        public string C_OfficeName { get; set; }
        public string C_PostCode { get; set; }
        public string C_PostName { get; set; }
        public string C_StaffCode { get; set; }
        public string C_StaffName { get; set; }
        public string C_ShiftCode { get; set; }
        public string C_ShiftName { get; set; }
        public Nullable<int> L_Complete { get; set; }
        public Nullable<int> L_WorkState { get; set; }
        public Nullable<int> L_InTime { get; set; }
        public Nullable<int> L_OutTime { get; set; }
        public Nullable<int> L_LateTime { get; set; }
        public Nullable<int> L_LackTime { get; set; }
        public Nullable<int> L_MultiRange { get; set; }
        public Nullable<int> L_WT1In { get; set; }
        public Nullable<int> L_WT1Out { get; set; }
        public Nullable<int> L_WT1Late { get; set; }
        public Nullable<int> L_WT1Lack { get; set; }
        public Nullable<int> L_WT1Time { get; set; }
        public Nullable<int> L_WT2In { get; set; }
        public Nullable<int> L_WT2Out { get; set; }
        public Nullable<int> L_WT2Late { get; set; }
        public Nullable<int> L_WT2Lack { get; set; }
        public Nullable<int> L_WT2Time { get; set; }
        public Nullable<int> L_WT3In { get; set; }
        public Nullable<int> L_WT3Out { get; set; }
        public Nullable<int> L_WT3Late { get; set; }
        public Nullable<int> L_WT3Lack { get; set; }
        public Nullable<int> L_WT3Time { get; set; }
        public Nullable<int> L_WT4In { get; set; }
        public Nullable<int> L_WT4Out { get; set; }
        public Nullable<int> L_WT4Late { get; set; }
        public Nullable<int> L_WT4Lack { get; set; }
        public Nullable<int> L_WT4Time { get; set; }
        public Nullable<int> L_WT5In { get; set; }
        public Nullable<int> L_WT5Out { get; set; }
        public Nullable<int> L_WT5Late { get; set; }
        public Nullable<int> L_WT5Lack { get; set; }
        public Nullable<int> L_WT5Time { get; set; }
        public Nullable<int> L_WT6In { get; set; }
        public Nullable<int> L_WT6Out { get; set; }
        public Nullable<int> L_WT6Late { get; set; }
        public Nullable<int> L_WT6Lack { get; set; }
        public Nullable<int> L_WT6Time { get; set; }
        public Nullable<double> D_PayMoney { get; set; }
        public Nullable<int> L_Modify { get; set; }
        public string C_Remark { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
